db.RedSocial.insertMany([

    {Nombre: "Fernando",
    Apellidos: "Galvez",
    Publicaciones: 150,
    NombresUsuarios: ["FG", "FerGal"],
    NumPublicaciones: { Fotos: 55, Videos: 45, Frases: 50},
    HorasDeUso: 56,
    Premium: true,
    FechaIngreso: new Date(2008,9,21),
    Direccion: "Calle Nueva York",
    CodPost: 41008,
    Telefono: 665665987},

    {Nombre: "Maria",
    Apellidos: "Fernandez",
    Publicaciones: 3,
    NombresUsuarios: ["MF", "MarFer"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 1},
    HorasDeUso: 6,
    Premium: false,
    FechaIngreso: new Date(2012,1,1),
    CodPost: 41018,},

    {Nombre: "Gonzalo",
    Apellidos: "Marin",
    Publicaciones: 23,
    NombresUsuarios: ["GM", "GonMar"],
    NumPublicaciones: { Fotos: 20, Frases: 3},
    HorasDeUso: 34,
    Premium: false,
    FechaIngreso: new Date(2020,5,3)},

    {Nombre: "Rafael",
    Apellidos: "Gallardo",
    NombresUsuarios: ["RG", "RafGal"],
    HorasDeUso: 29,
    Premium: false,
    FechaIngreso: new Date(2019,12,23),
    Direccion: "Calle Permaldo",
    CodPost: 41012},

    {Nombre: "Berta",
    Apellidos: "Tomares",
    Publicaciones: 5,
    NombresUsuarios: ["BT", "BerTom"],
    NumPublicaciones: { Videos: 3 , Frases: 2 },
    HorasDeUso: 102,
    Premium: true,
    FechaIngreso: new Date(2015,6,30),
    CodPost: 41002,
    Telefono: 695665265},

    {Nombre: "Tomas",
    Apellidos: "Gutierrez",
    Publicaciones: 120,
    NombresUsuarios: ["TG", "TomGut"],
    NumPublicaciones: { Frases:120 },
    HorasDeUso: 234,
    Premium: true,
    FechaIngreso: new Date(2009,3,5)},

    {Nombre: "Lucia",
    Apellidos: "Garcia",
    NombresUsuarios: ["LG", "LucGar"],
    HorasDeUso: 1,
    Premium: false,
    FechaIngreso: new Date(2020,1,1),
    Direccion: "Calle Manteca",
    CodPost: 41018,
    Telefono: 669875665},

    {Nombre: "Ignacio",
    Apellidos: "Mora",
    NombresUsuarios: ["IM", "IgnMor"],
    Premium: false,
    FechaIngreso: new Date(2015,3,23)},

    {Nombre: "Marta",
    Apellidos: "Martinez",
    Publicaciones: 28,
    NombresUsuarios: ["MM", "MarMar"],
    NumPublicaciones: { Fotos:8 , Videos:19 , Frases:1 },
    HorasDeUso: 145,
    Premium: true,
    FechaIngreso: new Date(2013,9,9)},

    {Nombre: "Carlos",
    Apellidos: "Martinez",
    NombresUsuarios: ["CM", "CarMar"],
    Premium: true,
    FechaIngreso: new Date(2017,6,16),
    Direccion: "Calle Benidorm",
    CodPost: 41018,
    Telefono: 665665665},

    {Nombre: "Carlos",
    Apellidos: "Gutierrez",
    Publicaciones: 120,
    NombresUsuarios: ["CG", "CarGut"],
    NumPublicaciones: { Videos:20 , Frases:100 },
    HorasDeUso: 50,
    Premium: false,
    FechaIngreso: new Date(2002,4,12),
    CodPost: 41017,
    Direccion:"Calle Bambino"},

    {Nombre: "Alicia",
    Apellidos: "Lorenzo",
    Publicaciones: 76,
    NombresUsuarios: ["AL", "AliLor"],
    NumPublicaciones: { Fotos:70 , Frases:6 },
    HorasDeUso: 45,
    Premium: false,
    FechaIngreso: new Date(2018,9,9)},

    {Nombre: "Roberto",
    Apellidos: "Madrid",
    Publicaciones: 12,
    NombresUsuarios: ["RM", "RobMad"],
    NumPublicaciones: { Fotos:2 , Videos:2 , Frases:8 },
    HorasDeUso: 672,
    Premium: true,
    FechaIngreso: new Date(2013,10,2)},

    {Nombre: "Martina",
    Apellidos: "Suarez",
    NombresUsuarios: ["", ""],
    Premium: false,
    FechaIngreso: new Date(2020,12,1),
    Telefono: 666789987},

    {Nombre: "Blanca",
    Apellidos: "Suarez",
    Publicaciones: 25,
    NombresUsuarios: ["BS", "BlaSua"],
    NumPublicaciones: { Fotos: 5, Videos: 20 },
    HorasDeUso: 2,
    Premium: true,
    FechaIngreso: new Date(2015,10,10),
    Direccion: "Calle Primera",
    CodPost:43012},

    {Nombre: "Miguel",
    Apellidos: "Ramos",
    NombresUsuarios: ["MR", "MigRam"],
    Premium: false,
    FechaIngreso: new Date(2009,4,12)},

    {Nombre: "Paula",
    Apellidos: "Ramos",
    Publicaciones: 170,
    NombresUsuarios: ["PR", "PauRam"],
    NumPublicaciones: { Frases: 170 },
    HorasDeUso: 234,
    Premium: false,
    FechaIngreso: new Date(2013,3,21)},

    {Nombre: "Fernanda",
    Apellidos: "Montero",
    Publicaciones: 12,
    NombresUsuarios: ["FM", "FerMon"],
    NumPublicaciones: { Fotos: 2, Videos: 10 },
    HorasDeUso: 12,
    Premium: true,
    FechaIngreso: new Date(2018,2,28),
    Direccion: "Calle Betis"},

    {Nombre: "Fernando",
    Apellidos: "Romero",
    Publicaciones: 23,
    NombresUsuarios: ["FR", "FerRom"],
    NumPublicaciones: { Fotos: 21, Videos: 1, Frases: 1 },
    HorasDeUso: 12,
    Premium: true,
    FechaIngreso: new Date(2000,12,1)},

    {Nombre: "Juan",
    Apellidos: "Sanchez",
    Publicaciones: 1,
    NombresUsuarios: ["JS", "JuaSan"],
    NumPublicaciones: { Videos:1 },
    HorasDeUso: 2,
    Premium: false,
    FechaIngreso: new Date(2020,11,20),
    Telefono:182787872,
    CodPost:12341},

    {Nombre: "Pedro",
    Apellidos: "Juarez",
    Publicaciones: 10,
    NombresUsuarios: ["PJ", "PedJua"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 8 },
    HorasDeUso: 7,
    Premium: true,
    FechaIngreso: new Date(2000,11,20),
    CodPost:41015},

    {Nombre: "Domingo",
    Apellidos: "Dominguez",
    Publicaciones: 150,
    NombresUsuarios: ["DD", "DomDom"],
    NumPublicaciones: { Fotos: 50, Videos: 100 },
    HorasDeUso: 7,
    Premium: false,
    FechaIngreso: new Date(2010,1,2)},

    {Nombre: "Angeles",
    Apellidos: "Suarez",
    Publicaciones: 70,
    NombresUsuarios: ["AS", "AngSua"],
    NumPublicaciones: { Fotos: 29, Videos: 40, Frases: 1 },
    Premium: false,
    FechaIngreso: new Date(2000,11,20),
    Direccion: "Calle Reinos"},

    {Nombre: "Aurora",
    Apellidos: "Juarez",
    Publicaciones: 1,
    NombresUsuarios: ["AJ", "AurJua"],
    NumPublicaciones: { Fotos: 1 },
    HorasDeUso: 7,
    Premium: true,
    FechaIngreso: new Date(2012,12,10)},

    {Nombre: "Tomas",
    Apellidos: "Marquez",
    Publicaciones: 25,
    NombresUsuarios: ["TM", "TomMar"],
    NumPublicaciones: { Fotos: 10, Videos: 10, Frases: 5 },
    HorasDeUso: 7,
    Premium: false,
    FechaIngreso: new Date(2007,7,1)},

    {Nombre: "Jeronimo",
    Apellidos: "Martin",
    Publicaciones: 4,
    NombresUsuarios: ["JM", "JerMar"],
    NumPublicaciones: { Fotos: 1, Videos: 1, Frases: 2 },
    HorasDeUso: 7,
    Premium: false,
    FechaIngreso: new Date(2017,1,20),
    CodPost: 41013},

    {Nombre: "Antonio",
    Apellidos: "Romero",
    NombresUsuarios: ["AR", "AntRom"],
    Premium: false,
    FechaIngreso: new Date(2020,5,3),
    Direccion: "Calle Madrid",
    Telefono: 783893094,
    CodPost: 41012},

    {Nombre: "Patricia",
    Apellidos: "Velez",
    Publicaciones: 568,
    NombresUsuarios: ["PV", "PatVel"],
    NumPublicaciones: { Fotos: 500, Videos: 60, Frases: 8 },
    HorasDeUso: 7,
    Premium: false,
    FechaIngreso: new Date(2020,1,30),
    Direccion: "Calle Cuenca"},

    {Nombre: "Adrian",
    Apellidos: "Quevedo",
    Publicaciones: 1034,
    NombresUsuarios: ["AQ", "AdrQue"],
    NumPublicaciones: { Fotos: 504, Videos: 30, Frases: 500 },
    HorasDeUso: 712,
    Premium: true,
    FechaIngreso: new Date(2010,1,1)},

    {Nombre: "David",
    Apellidos: "Parejo",
    Publicaciones: 10,
    NombresUsuarios: ["DP", "DavPar"],
    NumPublicaciones: { Fotos: 10 },
    HorasDeUso: 7,
    Premium: true,
    FechaIngreso: new Date(2001,9,9),
    Telefono: 657849499},

    {Nombre: "Pedro",
    Apellidos: "Sanchez",
    Publicaciones: 45,
    NombresUsuarios: ["PS", "PedSan"],
    NumPublicaciones: { Fotos: 5, Videos: 20, Frases: 20 },
    HorasDeUso: 445,
    Premium: false,
    FechaIngreso: new Date(2002,11,30)},

]);